version: '3'
services:
  mysql:
    image: public.ecr.aws/docker/library/mysql:8.3.0
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: food
      LANG: C.UTF_8
    command: --init-file /data/application/food.sql
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    volumes:
      - ./volumes/db/mysql:/var/lib/mysql
      - ./volumes/db/food.sql:/data/application/food.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  api:
    image: node43/api-food:local
    build:
      dockerfile: Dockerfile
      context: ../source
    restart: always
    container_name: api-food
    environment:
      DB_NAME: food
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_PORT: 3306
      DB_DIALECT: mysql
      FOOD_APP_SERVER_PORT: 3000
      FOOD_APP_CONTEXT_PATH: /food-app
      FOOD_APP_SALT: 10
      FOOD_APP_JWT_SECRET: ee487dbacf3b96b9bcbd568d7e37aff917c3867d1565de671c47de125dc3f809
      FOOD_APP_JWT_EXPIRES_IN: 1h
    ports:
      - 3000:3000
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    depends_on:
      mysql: 
        condition: service_healthy
networks:
  default:
    name: local
    external: true